### PR TITLE
Add support for unix sockets

### LINKED ISSUE #30: Add support for unix sockets
currently, only TCP is supported

### PR DESCRIPTION
**Pull request by wews64**
resolve #30

### CODE REVIEW

**Comment by davebryson** [comment]
@wews64 @melekes   Thanks! looks good!  
I have one suggestion.  Why not just parse the address and simply select the appropriate listener versus duplicating code here:  
https://github.com/tendermint/rust-abci/pull/47/files#diff-4ce93534efc34e923ce01e975eb7ed80R14

Example:  if the address starts with `unix` use the UnixListener,  otherwise use the tcp listener.  The rest of the code stays the same and you can eliminate the whole `serve_unix` function

**Comment by wews64** [comment]
@davebryson
I can not remove duplicating code, because there different types of incoming connections `std::os::unix::net::UnixStream` and `std::net::TcpStream`. I can make common interface for both functions, something like `pub fn serve<A>(app: A, addr: &str) -> io::Result<()>`. But it, under the hood, will also call different handlers.

**Comment by tomtau** [comment]
@wews64 I'm not sure whether this works, but you could possibly pass in the `listener` as an argument, constructed based on the address type.  Both `UnixStream` and `TcpStream` implement `IntoIterator`, so perhaps the listener argument could have a type like `IntoIterator<Item=Result<S, E>>` (where `S` is the stream, so something like `S: Read + Write`) and instead of:
```
for new_connection in listener.incoming() {
...
```

you could do:
```
for new_connection in listener.into_iter() {
...
```

**Comment by wews64** [comment]
@tomtau but on next step i'm must send specific type (`UnixStream` or `TcpStream`) in `AbciStream::from`.

**Comment by tomtau** [comment]
@wews64 just a correction -- when I wrote `UnixStream` and `TcpStream`, I meant `UnixListener` and `TcpListener`. For streams themselves, what if you constrain `S` more? Something like `S: Read + Write + Into<AbciStream>`?

**Comment by tomtau** [comment]
@wews64 there has been quite a lot of changes in the meantime (e.g. tokio was added), so will close this PR for the moment -- feel free to update your changes and open a new PR

**Pull request closed without merging**
