### PR TITLE
Tendermint 0.26 + Fix panic on too many/large transactions

### LINKED ISSUE #20: Panic on too many/large transactions
I'm running on Tendermint 0.25 with this patched version: https://github.com/tendermint/rust-tsp/pull/18/commits/90dad488d873dbda0ee29473cd61fdac5189110e

With too many/large transactions, rust-tsp will panic:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: WriteZero, error: StringError("failed to write whole buffer") }', libcore/result.rs:1009:5
```

stack backtrace:
```
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: std::panicking::try::do_call
             at libstd/panicking.rs:326
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: core::alloc::Layout::repeat
             at libcore/macros.rs:26
   9: <bytes::bytes::BytesMut as core::convert::AsRef<[u8]>>::as_ref
             at libcore/result.rs:808
  10: <protobuf::cached_size::CachedSize as core::default::Default>::default
             at ~/.cargo/git/checkouts/rust-tsp-6c1140b7f202a3ea/90dad48/src/server.rs:150
  11: abci::server::respond
             at ~/.cargo/git/checkouts/rust-tsp-6c1140b7f202a3ea/90dad48/src/server.rs:118
  12: abci::server::handle_stream
             at ~/.cargo/git/checkouts/rust-tsp-6c1140b7f202a3ea/90dad48/src/server.rs:62
  13: abci::server::serve::{{closure}}
             at ~/.cargo/git/checkouts/rust-tsp-6c1140b7f202a3ea/90dad48/src/server.rs:34
```

### PR DESCRIPTION
**Pull request by tomtau**
Fixes #20 

Tested with Tendermint 0.26.3

### CODE REVIEW

**Comment by melekes** [comment]
Can we get this rebased against latest master? Thanks

**Comment by melekes** [comment]
Looks good to me!

@JacksonCoder @davebryson I'd appreciate if you guys find some time for a quick review.

**Comment by davebryson** [comment]
This will work for sure.  It'd be nice to add more tests since `NetStream` has been added.

While we're fiddling with this, I wonder though if it would be better to do a bit of refactoring and just allocate (create) `BytesMut` based on the actual size of the response - versus preallocating it with `BUFFER_SIZE` and then doing the additional checks and the potential call to `reserve`?

**Comment by tomtau** [comment]
@melekes rebased.

@davebryson I agree, but it may be better to open separate smaller issues and PRs for that. Besides more tests, here are a few points I'd like to fix:

1) The current fix only helps with responses, but it's still possible to get a panic here: https://github.com/tendermint/rust-abci/blob/c947920845fe642d9f32807ba5d161476c9c2cee/src/server.rs#L99
e.g. if one sends a very large QueryRequest. But this is a separate issue and I'm not yet sure what the best way to pre-allocate is for requests from streams -- perhaps bound it to the max block bytes consensus parameter? Or make use of that TM convention (https://github.com/tendermint/tendermint/wiki/Application-Developers#async-raw) on the receiving side?

> Messages coming over the socket are Protobuf3 encoded, but additionally length-prefixed to facilitate use as a streaming protocol. Protobuf3 doesn't have an official length-prefix standard, so we use our own. The first byte in the prefix represents the length of the Big Endian encoded length. The remaining bytes in the prefix are the Big Endian encoded length.

2) Add a support for unix sockets to NetStream.

3) Have a way to distinguish between connections (info, mempool, consensus) and have a relaxed trait that wouldn't need to mutate the app on requests from info and mempool, so that there's no need for the mutex.

4) Have additional sanity checks on the ABCI protocol execution, so that the client app doesn't need to worry about them -- e.g. use https://docs.rs/session_types/0.2.0/session_types/

**Comment by melekes** [comment]
Merged. Thanks everyone 👍 

@tomtau feel free to open a new issue (or many small ones).

**Pull request merged**
